name: Abby
description: "Flutter Ollama UI"
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  flutter_markdown: ^0.7.1
  file_selector: ^1.0.3
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  intl: ^0.19.0
  logging: ^1.2.0
  markdown: ^7.2.2
  ollama_dart: ^0.1.1
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: '>=0.1.0-dev.1'
  url_launcher: ^6.2.6
  ndjson: ^0.2.2
  uuid: ^4.4.0
  link_text: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.7

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/app_icons/abbylogo.png
    - assets/persona/Portrait_Placeholder.png
    - assets/persona/Abby.webp
  fonts:
    - family: SourceCode
      fonts:
        - asset: assets/fonts/SourceCodePro.ttf
        - asset: assets/fonts/SourceCodePro-Italic.ttf
          style: italic
